# Permalinks
#
permalink:           pretty

# Setup
title:               iFraud
tagline:             'Random Scratch Book'
description:         'A place to dump everything.'
url:                 http://ifraud.github.io
baseurl:             http://ifraud.github.io
paginate:            4

# About/contact
author:
  name:              Vamsidhar Reddy Gaddam
  url:               https://ifraud.github.io
  email:             gaddam.vamsidhar@gmail.com

# Custom vars
version:             1.0.0
